// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'index', // This points to docs/index.md
        },
        {
          type: 'doc',
          id: 'introduction', // This points to docs/introduction.md
        },
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-0-foundations',
        },
        {
          type: 'autogenerated',
          dirName: 'module-1-ros2',
        },
        {
          type: 'autogenerated',
          dirName: 'module-2-simulation',
        },
        {
          type: 'autogenerated',
          dirName: 'module-3-isaac',
        },
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
    },
  ],
};

module.exports = sidebars;